- name: Basic Health Check
  hosts: servers
  tasks:
    - name: Check Disk Usage
      command: df -h
      register: disk_usage

    - name: Check CPU Usage
      shell: "grep 'cpu ' /proc/stat"
      register: cpu_usage

    - name: Check Memory Usage
      command: free -h
      register: memory_usage

    - name: Write Health Report to File
      local_action: copy content="{{ disk_usage.stdout }}\n{{ cpu_usage.stdout }}\n{{ memory_usage.stdout }}" dest=/var/lib/jenkins/workspace/Health Check Job/health_report.txt

